package com.warpedreality.lostpowers;

import com.warpedreality.lostpowers.commands.CommandDimensionTP;
import com.warpedreality.lostpowers.commands.CommandHeal;
import com.warpedreality.lostpowers.init.ModSmelting;
import com.warpedreality.lostpowers.proxy.CommonProxy;
import com.warpedreality.lostpowers.utils.Utils;
import com.warpedreality.lostpowers.utils.handlers.EventHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;

@Mod(
        modid = Reference.MODID,
        name = Reference.NAME,
        version = Reference.VERSION
)
public class Main {
    @Mod.Instance
    public static Main instance;

    @SidedProxy(clientSide = Reference.CLIENT_PROXY_CLASS, serverSide = Reference.COMMON_PROXY_CLASS)
    public static CommonProxy proxy;

    @Mod.EventHandler
    public static void PreInit(FMLPreInitializationEvent event) {
        Utils.log().info("Pre Initialization");

        Utils.log().info("Setting Mod Metadata...");
        ModMetadata modMetadata = event.getModMetadata();
        modMetadata.modId = Reference.MODID;
        modMetadata.name = Reference.NAME;
        modMetadata.description = Reference.DESC;
        modMetadata.version = Reference.VERSION;
        modMetadata.authorList = Reference.AUTHOR;
        modMetadata.autogenerated = false;
        modMetadata.credits = Reference.CREDITS;

        Utils.log().info("Loading Config PreInit...");
        Config.PreInit(event);
    }

    @Mod.EventHandler
    public static void Init(FMLInitializationEvent event) {
        Utils.log().info("Initialization");

        Utils.log().info("Registering Recipes...");
        ModSmelting.register();

        Utils.log().info("Registering Events...");
        EventHandler.register();

        Utils.log().info("Loading Config Init...");
        Config.Init(event);
    }

    @Mod.EventHandler
    public static void PostInit(FMLPostInitializationEvent event) {
        Utils.log().info("Post Initialization");

        Utils.log().info("Loading Config PostInit...");
        Config.PostInit(event);
    }

    @Mod.EventHandler
    public void serverStart(FMLServerStartingEvent event)
    {
        Utils.log().info("Server Starting");

        Utils.log().info("Registering Server Commands...");

        //Utils.log().info("Registered Command > CommandHeal");
        //event.registerServerCommand(new CommandHeal());
        Utils.log().info("Registered Command > CommandDimensionTP");
        event.registerServerCommand(new CommandDimensionTP());
        //Utils.log().info("Registered Command > CommandYourTheBoss");
        //event.registerServerCommand(new CommandYourTheBoss());
    }
}
