package com.tastycake.hiddenpowers;

import com.tastycake.hiddenpowers.init.ModSmelting;
import com.tastycake.hiddenpowers.proxy.CommonProxy;
import com.tastycake.hiddenpowers.utils.Utils;
import com.tastycake.hiddenpowers.utils.handlers.EventHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(
        modid = Reference.MODID,
        name = Reference.NAME,
        version = Reference.VERSION
)
public class Main {
    @Mod.Instance
    public static Main instance;

    @SidedProxy(clientSide = Reference.CLIENT_PROXY_CLASS, serverSide = Reference.COMMON_PROXY_CLASS)
    public static CommonProxy proxy;

    @Mod.EventHandler
    public static void PreInit(FMLPreInitializationEvent event) {
        Utils.log().info("Pre Initialization");

        Utils.log().info("Setting Mod Metadata...");
        ModMetadata modMetadata = event.getModMetadata();
        modMetadata.modId = Reference.MODID;
        modMetadata.name = Reference.NAME;
        modMetadata.description = Reference.DESC;
        modMetadata.version = Reference.VERSION;
        modMetadata.authorList = Reference.AUTHOR;
        modMetadata.autogenerated = false;
        modMetadata.credits = Reference.CREDITS;
    }

    @Mod.EventHandler
    public static void Init(FMLInitializationEvent event) {
        Utils.log().info("Initialization");

        Utils.log().info("Registering Recipes...");
        ModSmelting.register();

        Utils.log().info("Registering Events...");
        EventHandler.register();
    }

    @Mod.EventHandler
    public static void PostInit(FMLPostInitializationEvent event) {
        Utils.log().info("Post Initialization");
    }
}
